version: '3'
services:
  doctor:
    build:
      context: ./doctor-biz
    restart: always
    container_name: doctor
    hostname: doctor
    image: doctor
    environment:
      - PATIENT_ADDRESS
      - QRCODE_ADDRESS
    networks:
      - spring_cloud_default
    volumes:
      - /home/changshun/pig-data:/home/test/pig-data

networks:
  spring_cloud_default:
    name: spring_cloud_default
    driver: bridge
