server:
  port: 7002

web:
  qrcode: /home/test/pig-data/qrcode

spring:
  web:
    resources:
      static-locations: file:${web.qrcode}/ # 静态资源路径，注意需要添加“/”
  profiles:
    active: prod # 部署时一定是prod才行，linux服务器测试可以使用dev借助IDEA远程运行