server:
  port: 7001

spring:
  profiles:
    active: prod  # 部署时一定是prod才行，linux服务器测试可以使用dev借助IDEA远程运行

wxchat:
  appid: wxe23d19faaffb93f6
  secret: e65f9a193d0d395c1fbf89a38796071f
  enc_key: thanks,pig4cloud
hardware:
  url: http://8.147.235.227:12345/api/users # 硬件设备请求数据接口
  appid: bp_ezjsiejrziojwieo
  sec: ${APP_SECRET}
  callback_url: ${CALLBACK_URL:https://zhxkcs.4thservice.org/api/patient/patientDeviceV2/callback}
